### ISSUE TITLE
React v15.5 deprecating React.PropTypes

### ISSUE THREAD

**Issue by aribronstein** [bsidelinger912/shiitake#10]
Can you please update to support the breaking change coming in v16?

**Comment by bsidelinger912** [comment]
Hey @aribronstein, I started working on this tonight along with upgrading a handful of packages, I've got an issue with karma-webpack, but once I'm through that I should have this done.

**Comment by bsidelinger912** [comment]
Hey @aribronstein, so it seems the change is not breaking if you use PropTypes in the normal way per this article: https://facebook.github.io/react/warnings/dont-call-proptypes.html.  But since it is deprecated I went ahead and updated to use the prop-types library, as well as updating some other dependancies.  The latest version, 2.0.1 has these updates.

**Comment by aribronstein** [comment]
Thanks, updated and everything seems to be working great.

**Comment by bsidelinger912** [comment]
Awesome!
